version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nest-auth
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
